apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ghcp-staging
resources:
  - ../../../migration
images:
  - name: registry.invalid/ghcp-pool-proxy/migration
    newName: pczhao1210/ghcp-pool-proxy
    newTag: migration-latest
labels:
  - pairs:
      app.kubernetes.io/environment: staging
    includeSelectors: false
    includeTemplates: true
