apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common
  - migration-job.yaml
labels:
  - pairs:
      app.kubernetes.io/name: ghcp-pool-proxy
      app.kubernetes.io/part-of: ghcp-pool-proxy
    includeSelectors: false
    includeTemplates: true
