apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-monitors.yaml
labels:
  - pairs:
      app.kubernetes.io/name: ghcp-pool-proxy
      app.kubernetes.io/part-of: ghcp-pool-proxy
      app.kubernetes.io/component: monitoring
    includeSelectors: false
    includeTemplates: true
